services:
  mongodb:
    image: mongo:7
    container_name: gestor-permisos-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - travelconnect-net

  backend:
    image: chivaa8/travelconnect-backend:1.0
    build:
      context: ./backend
    container_name: gestor-permisos-backend
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
    environment:
      PORT: 3001
      MONGO_DB_URI: mongodb://mongodb:27017/gestorPermisosLaborables
      JWT_SECRET: cambia-este-secreto-en-produccion
      BCRYPT_ROUNDS: 10
      FRONTEND_URL: http://localhost:4200
    ports:
      - "3001:3001"
    networks:
      - travelconnect-net

  frontend:
    image: chivaa8/travelconnect-frontend:1.0
    build:
      context: ./frontend
    container_name: gestor-permisos-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - travelconnect-net

volumes:
  mongodb_data:

networks:
  travelconnect-net:
    driver: bridge
