services:
  mongodb:
    image: mongo:7
    container_name: gestor-permisos-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: gestor-permisos-backend
    depends_on:
      - mongodb
    environment:
      PORT: 3001
      MONGO_DB_URI: mongodb://mongodb:27017/gestorPermisosLaborables
      JWT_SECRET: cambia-este-secreto-en-produccion
      BCRYPT_ROUNDS: 10
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
    container_name: gestor-permisos-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  mongodb_data:
